services:
  postgres:
    image: postgres:16
    container_name: pfm_postgres
    restart: always
    environment:
      POSTGRES_DB: pfm_db
      POSTGRES_USER: pfm_user
      POSTGRES_PASSWORD: pfm_pass
    ports:
      - "5432:5432"
    volumes:
      - pfm_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pfm_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pfm_db
      SPRING_DATASOURCE_USERNAME: pfm_user
      SPRING_DATASOURCE_PASSWORD: pfm_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pfm_data:
